import { Event, FAQ, VendorCategory } from './types';

export const EVENTS_DATA: Event[] = [
  {
    id: 'ev-01',
    title: 'Artisanal Heritage Market',
    date: 'Oct 14-15, 2026',
    location: 'Arts District, Los Angeles',
    image: 'https://i.pinimg.com/1200x/c7/b0/f9/c7b0f905e7f9e683a38a5d71dead6cc7.jpg',
    spotsLeft: 12,
    totalSpots: 40,
    tag: 'Los Angeles',
    category: 'Artisanal & Crafts',
    description: 'A curated showcase of premier craft makers, organic purveyors, and boutique local brands. Situated in the heart of LA’s cultural hub, attracting affluent design and culinary enthusiasts.',
    cost: '$450 / Weekend',
    attendance: '15,000+ expected',
    highlight: 'Includes 10x10 premium tent space, professional lighting canopy, and spotlight promotions.'
  },
  {
    id: 'ev-02',
    title: 'Smoke & Oak Spirits Fest',
    date: 'Nov 02, 2026',
    location: 'Coconut Grove, Miami',
    image: 'https://i.pinimg.com/1200x/90/7e/7d/907e7d060e7408ed7dcce2c4eab50699.jpg',
    spotsLeft: 0,
    totalSpots: 35,
    tag: 'Miami',
    category: 'Spirits & BBQ',
    description: 'An exclusive single-day pairing event. Highlighting craft distilleries, premium barrel-aged whiskey, and artisanal smoked meats under the coastal night breeze.',
    cost: '$600 / Day',
    attendance: '8,000+ expected',
    highlight: 'Includes heavy-duty 20A electricity, private waste service, and ice-supply concierge.'
  },
  {
    id: 'ev-03',
    title: 'Ember & Spice Street Fair',
    date: 'Nov 22, 2026',
    location: 'Downtown, Austin',
    image: 'https://i.pinimg.com/1200x/7d/6f/6e/7d6f6e7c879cd8dc965704875d0d0936.jpg',
    spotsLeft: 4,
    totalSpots: 50,
    tag: 'Austin',
    category: 'Gourmet Culinary',
    description: 'Texas’ ultimate high-heat food festival. Celebrating regional pitmasters, hot sauce pioneers, and bold street food entrepreneurs. Known for lively music and fierce competition.',
    cost: '$500 / Weekend',
    attendance: '22,000+ expected',
    highlight: 'Includes water-hookup access, shared cold-storage lockers, and fire safety compliance support.'
  },
  {
    id: 'ev-04',
    title: 'Harvest Gala & Market',
    date: 'Dec 05-06, 2026',
    location: 'Chelsea Walk, New York City',
    image: 'https://i.pinimg.com/736x/94/a1/b3/94a1b31688dcb860b15936595959f854.jpg',
    spotsLeft: 6,
    totalSpots: 30,
    tag: 'New York City',
    category: 'Gourmet & Delicacies',
    description: 'An upscale winter-themed indoor food and luxury maker market. Perfect for premium gifting brands, gourmet chocolates, fine wines, and custom home lifestyle crafts.',
    cost: '$750 / Weekend',
    attendance: '18,000+ expected',
    highlight: 'Heated indoor environment, custom display booths, luxury concierge, and 24/7 security patrol.'
  },
  {
    id: 'ev-05',
    title: "The Butcher's Block",
    date: 'Jan 12, 2027',
    location: 'East Side, Austin',
    image: 'https://i.pinimg.com/1200x/e0/9e/8e/e09e8ecb54fb6a834b6e2b098617bf85.jpg',
    spotsLeft: 8,
    totalSpots: 25,
    tag: 'Austin',
    category: 'BBQ & Grilling',
    description: 'An elite culinary gathering for dry-aged steak houses, charcoal chefs, and knife makers. Heavily attended by restaurateurs and gourmet culinary buyers looking for new partnerships.',
    cost: '$550 / Day',
    attendance: '6,500+ expected',
    highlight: 'Access to high-capacity waste disposal, commercial-grade grease removal, and premium ash-bins.'
  },
  {
    id: 'ev-06',
    title: 'Coastal Crustacean & Wine',
    date: 'Feb 20-21, 2027',
    location: 'South Beach, Miami',
    image: 'https://i.pinimg.com/736x/25/5f/bf/255fbf9663d078e441f41a0e782cac7b.jpg',
    spotsLeft: 3,
    totalSpots: 45,
    tag: 'Miami',
    category: 'Seafood & Wine',
    description: 'A prestige waterfront beachside seafood festival. Pairing the finest catch with sustainable vineyard wines, boutique desserts, and ambient beachside live acoustic performance.',
    cost: '$650 / Weekend',
    attendance: '14,000+ expected',
    highlight: 'Ice-delivery service, shared refrigeration containers, waterfront guest seating, and overnight site security.'
  },
  {
    id: 'ev-07',
    title: 'Taco & Tequila Street Fiesta',
    date: 'Aug 16, 2026',
    location: '7101 S Buffalo Dr, Las Vegas',
    image: 'https://i.pinimg.com/736x/09/a1/19/09a11959c7b5fd731c50f3f4c2c6adca.jpg',
    spotsLeft: 14,
    totalSpots: 40,
    tag: 'Las Vegas',
    category: 'Tequila & Tacos',
    description: 'Get ready to fiesta with spicy tacos, bold tequila, and good vibes at the Taco & Tequila Street Fiesta!',
    cost: '$500 / Day',
    attendance: '16,000+ expected',
    highlight: 'Includes premium booth space, certified tequila sampling permitting support, and direct ice-supply concierge.',
    ticketLink: 'https://www.eventbrite.com/e/taco-tequila-street-fiesta-tickets-1992705609119'
  },
  {
    id: 'ev-08',
    title: 'Whiskey & BBQ Fest Miami',
    date: 'Apr 10-11, 2027',
    location: 'Coconut Grove, Miami',
    image: 'https://i.pinimg.com/736x/c6/04/5f/c6045ffbda797dc3a6753aacafea3473.jpg',
    spotsLeft: 18,
    totalSpots: 45,
    tag: 'Miami',
    category: 'Spirits & BBQ',
    description: "Florida's premier smokehouse and barrel pairing event. Featuring master smoke pitmasters and legendary craft whiskey distillers. Experience slow-cooked delicacies and smooth spirits by the marina.",
    cost: '$600 / Weekend',
    attendance: '12,000+ expected',
    highlight: 'Includes heavy-duty 20A electricity, dry-aged prep canopy access, and private wood-ash disposal.',
    ticketLink: 'https://www.eventbrite.com/e/whiskey-bbq-fest-miami-tickets-1992874413016'
  },
  {
    id: 'ev-09',
    title: 'American Hot Sauce and Spicy Food Expo',
    date: 'Jul 11, 2026',
    location: 'Austin Event Center, Austin',
    image: 'https://i.pinimg.com/736x/d5/09/8c/d5098c3328cb6a33ba5ce88b5522d308.jpg',
    spotsLeft: 22,
    totalSpots: 50,
    tag: 'Austin',
    category: 'Gourmet Culinary',
    description: 'The largest celebration of fire, flavor, and heat in the South — Austin, TX',
    cost: '$550 / Day',
    attendance: '20,000+ expected',
    highlight: 'Includes custom fire safety compliance, shared cold storage access, and featured showcase in the main mainstage heat contest.',
    ticketLink: 'https://www.eventbrite.com/e/american-hot-sauce-and-spicy-food-expo-tickets-1993070825491'
  },
  {
    id: 'ev-10',
    title: 'USA Street Eats & Craft Drinks Festival',
    date: 'Aug 21-23, 2026',
    location: 'Nevada Brew Works, Las Vegas',
    image: 'https://i.pinimg.com/736x/13/99/57/1399579283e193e65c8f13cf15e478da.jpg',
    spotsLeft: 25,
    totalSpots: 60,
    tag: 'Las Vegas',
    category: 'Street Food & Craft Beer',
    description: 'Dive into awesome street eats and craft drinks at the USA Street Eats & Craft Drinks Festival—foodie fun guaranteed!',
    cost: '$550 / Weekend',
    attendance: '25,000+ expected',
    highlight: 'Includes premium vendor space at Nevada Brew Works, high-amperage electrical hookups, direct ice access, and prominent digital mapping promotion.',
    ticketLink: 'https://www.eventbrite.com/e/usa-street-eats-craft-drinks-festival-tickets-1993339100910?aff=oddtdtcreator'
  },
  {
    id: 'ev-31',
    title: 'Miami Summer Vendor Market & Food Truck Festival',
    date: 'Jul 25-26, 2026',
    location: 'Regatta Grove, Coconut Grove, Miami',
    image: 'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 15,
    totalSpots: 40,
    tag: 'Miami',
    category: 'Street Food & Artisanal Crafts',
    description: 'The ultimate summer culinary and artisanal gathering at Regatta Grove. Explore Miami’s premier food trucks serving gourmet street eats, alongside curated local vendor booths displaying custom handcrafted jewelry, coastal crafts, and boutique summer apparel.',
    cost: '$450 / Weekend',
    attendance: '12,000+ expected',
    highlight: 'Includes 10x10 premium tent space or food truck docking spot, high-amperage electrical hookups, overnight site security, and digital map placement.',
    ticketLink: 'https://www.eventbrite.com/e/miami-summer-vendor-market-food-truck-festival-tickets-1991583813799?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=wsa&aff=ebdsshwebmobile'
  },
  {
    id: 'ev-11',
    title: 'L.A. Food Truck Extravaganza',
    date: 'Jun 20-21, 2026',
    location: 'Arts District, Los Angeles',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 45,
    tag: 'Los Angeles',
    category: 'Street Food',
    description: 'An outdoor culinary spectacle bringing together L.A.’s most iconic food trucks, from artisanal taco trucks to fusion dessert mobiles.',
    cost: '$400 / Weekend',
    attendance: '18,000+ expected',
    highlight: 'Premium parking spaces, waste disposal stations, and shared outdoor lounge areas.',
    isPast: true
  },
  {
    id: 'ev-12',
    title: 'Miami Tequila & Taco Fiesta',
    date: 'Jun 06, 2026',
    location: 'Coconut Grove, Miami',
    image: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 35,
    tag: 'Miami',
    category: 'Tequila & Tacos',
    description: 'A vibrant sun-soaked celebration of gourmet street tacos, certified blue agave tequilas, and live latin acoustic beats by the waterfront.',
    cost: '$500 / Day',
    attendance: '10,000+ expected',
    highlight: 'Waterfront breeze views, premium bar service equipment, and heavy-duty 20A electricity.',
    isPast: true
  },
  {
    id: 'ev-13',
    title: 'Austin Barbecue Heritage Fest',
    date: 'May 16-17, 2026',
    location: 'East Side, Austin',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 50,
    tag: 'Austin',
    category: 'BBQ & Grilling',
    description: 'Deep in the heart of Texas, this legendary smoking event paired low-and-slow pitmasters with craft amber ales and acoustic country guitar.',
    cost: '$600 / Weekend',
    attendance: '25,000+ expected',
    highlight: 'Access to high-capacity ash pits, dedicated wood-refuel stations, and grease management.',
    isPast: true
  },
  {
    id: 'ev-14',
    title: 'NYC Wine & Cheese Salon',
    date: 'May 02, 2026',
    location: 'Chelsea Walk, New York City',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 30,
    tag: 'New York City',
    category: 'Wine & Cheese',
    description: 'An intimate, upscale indoor tasting salon. Pairing boutique sustainable vineyard bottles with rare cave-aged international cheeses.',
    cost: '$700 / Day',
    attendance: '5,000+ expected',
    highlight: 'Heated indoor ambient hall, custom sommelier table displays, and 24/7 building security.',
    isPast: true
  },
  {
    id: 'ev-15',
    title: 'Vegas Craft Brewing Summit',
    date: 'Apr 18-19, 2026',
    location: '7101 S Buffalo Dr, Las Vegas',
    image: 'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 40,
    tag: 'Las Vegas',
    category: 'Street Food & Craft Beer',
    description: 'Nevada’s largest assembly of independent microbreweries, serving dry-hopped IPAs, barrel-aged stouts, and hearty pub snacks.',
    cost: '$550 / Weekend',
    attendance: '16,000+ expected',
    highlight: 'Indoor cooling fans, keg storage refrigeration access, and customized sample glass distribution.',
    isPast: true
  },
  {
    id: 'ev-16',
    title: 'LA Artisanal Chocolate Expo',
    date: 'Apr 04, 2026',
    location: 'Arts District, Los Angeles',
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 30,
    tag: 'Los Angeles',
    category: 'Gourmet & Delicacies',
    description: 'A decadent gathering of single-origin craft chocolatiers, hand-rolled truffles, and rich dessert wines in the Arts District.',
    cost: '$450 / Day',
    attendance: '8,500+ expected',
    highlight: 'Air-conditioned premium pavilion, elegant display shelving, and spotlight marketing.',
    isPast: true
  },
  {
    id: 'ev-17',
    title: 'Miami Coastal Craft & Design Market',
    date: 'Mar 21-22, 2026',
    location: 'South Beach, Miami',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 40,
    tag: 'Miami',
    category: 'Artisanal & Crafts',
    description: 'An eclectic beachside marketplace showcasing hand-poured candles, coastal ceramics, minimalist home design, and lightweight linen apparel.',
    cost: '$400 / Weekend',
    attendance: '12,000+ expected',
    highlight: 'Premium white-canopy standard tents, nighttime string light installation, and overnight watch.',
    isPast: true
  },
  {
    id: 'ev-18',
    title: 'Austin Hot Sauce Challenge',
    date: 'Mar 07, 2026',
    location: 'Downtown, Austin',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 50,
    tag: 'Austin',
    category: 'Gourmet Culinary',
    description: 'An intense single-day battle where small-batch hot sauce creators put their fieriest formulas to the ultimate community vote.',
    cost: '$450 / Day',
    attendance: '11,000+ expected',
    highlight: 'Custom safety compliance marshals, ice supply refills, and mainstage presenter slot.',
    isPast: true
  },
  {
    id: 'ev-19',
    title: 'NYC Hot Toddy & Cider Warm-Up',
    date: 'Feb 14-15, 2026',
    location: 'Chelsea Walk, New York City',
    image: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 35,
    tag: 'New York City',
    category: 'Spirits & BBQ',
    description: 'A cozy mid-winter celebration showcasing hot spiced rums, artisanal apple ciders, and wood-fired comfort foods.',
    cost: '$650 / Weekend',
    attendance: '9,000+ expected',
    highlight: 'Indoor heated booths, electric heater connections, and custom branded mugs for guests.',
    isPast: true
  },
  {
    id: 'ev-20',
    title: 'Las Vegas Neon Nights Market',
    date: 'Feb 01, 2026',
    location: '7101 S Buffalo Dr, Las Vegas',
    image: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 35,
    tag: 'Las Vegas',
    category: 'Artisanal & Crafts',
    description: 'An energetic evening market under glowing lights, presenting custom neon art, high-concept visual items, and experimental street bites.',
    cost: '$500 / Day',
    attendance: '14,000+ expected',
    highlight: 'Enhanced outdoor power grids, decorative overhead retro lighting, and live DJ audio system.',
    isPast: true
  },
  {
    id: 'ev-21',
    title: 'LA Winter Harvest & Craft Bazaar',
    date: 'Jan 17-18, 2026',
    location: 'Arts District, Los Angeles',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 40,
    tag: 'Los Angeles',
    category: 'Artisanal & Crafts',
    description: 'A warm and inviting celebration of winter farm produce, organic body care, and bespoke woodcarvings in southern California.',
    cost: '$450 / Weekend',
    attendance: '13,000+ expected',
    highlight: 'Double-wide booths, premium marketing spotlight, and access to electrical hookups.',
    isPast: true
  },
  {
    id: 'ev-22',
    title: 'Miami Rum & Reggae Fest',
    date: 'Jan 03, 2026',
    location: 'South Beach, Miami',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 30,
    tag: 'Miami',
    category: 'Spirits & BBQ',
    description: 'Kick off the new year with premium Caribbean rums, jerk-infused barbecue skewers, and relaxed beachside reggae grooves.',
    cost: '$550 / Day',
    attendance: '10,500+ expected',
    highlight: 'Waterfront access, dedicated ice and refrigeration containers, and private security.',
    isPast: true
  },
  {
    id: 'ev-23',
    title: 'Austin Smoked Rib & Beer Rally',
    date: 'Dec 13-14, 2025',
    location: 'East Side, Austin',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 45,
    tag: 'Austin',
    category: 'BBQ & Grilling',
    description: 'Texas-style pork rib competition paired with independent microbreweries. A delicious end-of-year culinary block party.',
    cost: '$500 / Weekend',
    attendance: '20,000+ expected',
    highlight: 'Commercial grade grease removal, water supply hookup, and ash bins.',
    isPast: true
  },
  {
    id: 'ev-24',
    title: 'NYC Holiday Gourmet & Gift Gala',
    date: 'Nov 29-30, 2025',
    location: 'Chelsea Walk, New York City',
    image: 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 50,
    tag: 'New York City',
    category: 'Gourmet & Delicacies',
    description: 'The premier holiday shopping event for gourmet gift baskets, hand-crafted stocking stuffers, artisanal panettones, and vintage wines.',
    cost: '$800 / Weekend',
    attendance: '22,000+ expected',
    highlight: 'Luxury indoor carpeted booths, 24/7 security patrol, and winter concierge packaging station.',
    isPast: true
  },
  {
    id: 'ev-25',
    title: 'Vegas Desert Solstice Gathering',
    date: 'Nov 15, 2025',
    location: 'Nevada Brew Works, Las Vegas',
    image: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 30,
    tag: 'Las Vegas',
    category: 'Gourmet Culinary',
    description: 'Celebrating desert culinary innovations, prickly pear cocktails, mesquite wood grilling, and native artisanal pottery.',
    cost: '$450 / Day',
    attendance: '7,500+ expected',
    highlight: 'Shaded structure, standard 110V power feed, and shared prep refrigeration lock.',
    isPast: true
  },
  {
    id: 'ev-26',
    title: 'LA Autumn Harvest Market',
    date: 'Oct 25-26, 2025',
    location: 'Arts District, Los Angeles',
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 40,
    tag: 'Los Angeles',
    category: 'Gourmet & Delicacies',
    description: 'An outdoor pumpkin-spiced culinary market featuring heirloom apples, freshly pressed ciders, and gourmet seasonal baked treats.',
    cost: '$450 / Weekend',
    attendance: '16,000+ expected',
    highlight: 'Premium central marketplace booth, social media influencer coverage, and power feed.',
    isPast: true
  },
  {
    id: 'ev-27',
    title: 'Miami Latin Street Food Carnival',
    date: 'Oct 11, 2025',
    location: 'South Beach, Miami',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 45,
    tag: 'Miami',
    category: 'Street Food & Craft Beer',
    description: 'A high-energy street fair celebrating Latin American cuisine—from Venezuelan arepas to cuban sandwiches—paired with local craft beers.',
    cost: '$550 / Day',
    attendance: '15,000+ expected',
    highlight: 'Ice supply refills, high-amperage electrical hookups, and direct water hookups.',
    isPast: true
  },
  {
    id: 'ev-28',
    title: 'Austin Handcrafted Leather & Goods Expo',
    date: 'Sep 27-28, 2025',
    location: 'Downtown, Austin',
    image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 35,
    tag: 'Austin',
    category: 'Artisanal & Crafts',
    description: 'Bringing together premium bootmakers, hand-tooled leather belts, custom denim jackets, and brass accessories in downtown Austin.',
    cost: '$450 / Weekend',
    attendance: '9,000+ expected',
    highlight: 'Premium spotlight placement, customized shelving rentals, and overnight indoor secure lockup.',
    isPast: true
  },
  {
    id: 'ev-29',
    title: 'NYC Rooftop Pinot & Seafood Soiree',
    date: 'Sep 13, 2025',
    location: 'Chelsea Walk, New York City',
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 30,
    tag: 'New York City',
    category: 'Seafood & Wine',
    description: 'A glamorous rooftop sunset tasting, combining cold-water oysters, fresh Maine lobster rolls, and chilled Oregon Pinot Noirs.',
    cost: '$750 / Day',
    attendance: '4,500+ expected',
    highlight: 'Rooftop panoramic view, specialized waste and oyster-shell disposal, and premium service canopy.',
    isPast: true
  },
  {
    id: 'ev-30',
    title: 'Vegas Brew & Brats Bash',
    date: 'Aug 23-24, 2025',
    location: 'Nevada Brew Works, Las Vegas',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    spotsLeft: 0,
    totalSpots: 35,
    tag: 'Las Vegas',
    category: 'Street Food & Craft Beer',
    description: 'A summer sausage and craft lager celebration at Nevada Brew Works, featuring gourmet hot dogs and ice-cold draft beers.',
    cost: '$500 / Weekend',
    attendance: '11,500+ expected',
    highlight: 'Standard canopy booth, live stage audio shoutouts, and high-amperage cooling systems.',
    isPast: true
  }
];

export const VENDOR_CATEGORIES: VendorCategory[] = [
  {
    id: 'cat-01',
    name: 'Hot Sauce Brands',
    description: 'Small-batch fiery formulations, artisanal pepper growers, and premium spice blends changing the spice landscape.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'cat-02',
    name: 'Food Trucks',
    description: 'Dynamic, state-of-the-art mobile kitchens delivering boundary-pushing gourmet food concepts and fusion treats.',
    image: 'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'cat-03',
    name: 'BBQ Pitmasters',
    description: 'True low-and-slow masters smoking premium briskets, heritage pork, and innovative wood-fired creations.',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'cat-04',
    name: 'Artisan Makers',
    description: 'Handcrafted premium knives, luxury pottery, organic cutting boards, and custom culinary kitchenware.',
    image: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'cat-05',
    name: 'Merchandise & Goods',
    description: 'Curated culinary apparel, handcrafted leather aprons, foodie lifestyle accessories, and gourmet cookbooks.',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80'
  }
];

export const FAQS_DATA: FAQ[] = [
  {
    id: 'faq-01',
    question: 'Do I need my own liability insurance?',
    answer: 'Yes. All vendors must provide a Certificate of Insurance (COI) naming valerianevents LLC as an additional insured. The general liability policy must have a minimum limit of $1,000,000 per occurrence. If you do not have insurance, we can refer you to our temporary event insurance partner for low-cost weekend coverage (approx. $45-$65).'
  },
  {
    id: 'faq-02',
    question: 'Is power provided at every booth?',
    answer: 'Absolutely. Every booth layout includes access to standard electricity (110V, 15A). For heavy culinary operations requiring dedicated high-power connections (such as 20A dedicated lines or 220V hookups), please specify this on your application forms. Premium power is available for a minor additional utility charge.'
  },
  {
    id: 'faq-03',
    question: 'What is the load-in schedule?',
    answer: 'For weekend events, load-in begins early Friday afternoon (from 1:00 PM to 6:00 PM) and finishes on Saturday morning (from 6:00 AM to 8:30 AM). You will be assigned a precise 30-minute vehicle arrival window to ensure a smooth, congestion-free load-in. All vehicles must exit the festival grounds by 9:00 AM.'
  },
  {
    id: 'faq-04',
    question: 'Can I share a booth with another brand?',
    answer: 'Yes, but both brands must be individually vetted and approved. You cannot sub-let your booth space or allow an unapproved vendor to display products under your canopy. If you wish to co-exhibit, please submit a joint application or contact Valerian directly before finalizing your booking.'
  },
  {
    id: 'faq-05',
    question: 'What happens in case of rain?',
    answer: 'All valerianevents matches are rain-or-shine. Our state-of-the-art clear-span canopies and custom lighting trusses protect the vendor and consumer walking corridors. In the rare event of extreme, hazardous weather (e.g., hurricane warnings or severe lightning storms), we will coordinate with local authorities to reschedule or offer full vendor credits.'
  },
  {
    id: 'faq-06',
    question: 'How are vendors selected?',
    answer: 'We seek premium brands with a strong commitment to quality, presentation, and culinary heritage. Our curation committee evaluates applications based on product uniqueness, visual booth styling, professional standards, food safety compliance, and synergy with other vendors. Space is limited to preserve high sales margins for all participants.'
  }
];

export const FOUNDER_DATA = {
  name: 'Valerian',
  title: 'Founder & Lead Organizer',
  bio: 'Valerian is the founder and driving force behind Valerian Events, an independent event organization company based in the United States specializing in food and spirits festivals.',
  email: 'alex@valerianevents.com',
  phone: '(727) 633-6611',
  avatar: 'https://i.pinimg.com/736x/3c/2b/ad/3c2badd0b9688bcb810ef699afc3f7c1.jpg',
  paymentMethod: 'Zelle (alex@valerianevents.com)',
  commitment: '24h response time guaranteed for all approved vendor inquiries.'
};
